services:
  knowledge-copilot:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: enterprise-knowledge-copilot

    ports:
      - "8501:8501"

    env_file:
      - .env

    volumes:
      - ./data/db:/app/data/db
      - ./data/monitoring:/app/data/monitoring

    restart: unless-stopped